global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
    params:
      collect[]:
        - "textfile"
    file_sd_configs:
      - files:
          - "/var/lib/node_exporter/ckptkit.prom"

  - job_name: "ckptkit_pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
